test_update.FrontEndUpdateTesting.test_ticketsuccess
----------------------------------------------------
Last Page: http://localhost:8081/update
  Browser: chrome
Timestamp: 1607894904  (Unix Timestamp)
     Date: Sunday, December 13, 2020
     Time: 4:28:24 PM  (Eastern Daylight Time, UTC-05:00)
----------------------------------------------------
Traceback: File "c:\users\emily\appdata\local\programs\python\python39-32\lib\unittest\case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "c:\users\emily\appdata\local\programs\python\python39-32\lib\unittest\case.py", line 550, in _callTestMethod
    method()
  File "c:\users\emily\appdata\local\programs\python\python39-32\lib\unittest\mock.py", line 1337, in patched
    return func(*newargs, **newkeywargs)
  File "C:\Users\emily\CISC-CMPE-327\qa327_test\frontend\test_update.py", line 338, in test_ticketsuccess
    self.assert_text("Listing update successful", "#updateMessage")
  File "c:\users\emily\appdata\local\programs\python\python39-32\lib\site-packages\seleniumbase\fixtures\base_case.py", line 5115, in assert_text
    self.wait_for_text_visible(text, selector, by=by, timeout=timeout)
  File "c:\users\emily\appdata\local\programs\python\python39-32\lib\site-packages\seleniumbase\fixtures\base_case.py", line 5063, in wait_for_text_visible
    return page_actions.wait_for_text_visible(
  File "c:\users\emily\appdata\local\programs\python\python39-32\lib\site-packages\seleniumbase\fixtures\page_actions.py", line 364, in wait_for_text_visible
    timeout_exception(ElementNotVisibleException, message)
  File "c:\users\emily\appdata\local\programs\python\python39-32\lib\site-packages\seleniumbase\fixtures\page_actions.py", line 117, in timeout_exception
    raise exc(message)
Exception: Message: 
 Expected text {Listing update successful} for {#updateMessage} was not visible after 6 seconds!
